# -*- coding: utf-8 -*-
"""ping_multiplo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDxA0-EwjoVYzBhA-URZqsn8ygOnECSS

Segurança de Informação com Python - Ping Múltiplo
Digital Innovation One - Instrutor Bruno Dias
Aluna: Mirian Ajiki Molicawa
"""

#importação das biblioteca os e time
import os
import time

# Abrir o arquivo de texto 
with open('hosts.txt') as file:
# Criação da variável para realizar a leitura do arquivo
  dump = file.read()
# Impressão do conteúdo do arquivo
  print(dump)

# Abrir o arquivo de texto 
with open('hosts.txt') as file:
# Criação da variável para realizar a leitura do arquivo 
    dump = file.read()  #Ficou na vertical a exibição das informações
    dump = dump.splitlines()  # Exbição em horizontal das informações
# Utilização do comando For para leitura da variáveil ip    
    for ip in dump: 
     print(ip)
     os.system('ping ' + ip)
     os.system('ping -n 2 {}'.format(ip))  #2 pacotes sendos enviados

# Abrir o arquivo de texto 
with open('hosts.txt') as file:
# Criação da variável para realizar a leitura do arquivo 
    dump = file.read()  #Ficou na vertical o conteúdo do arquivo linha a linha
    dump = dump.splitlines()  # Junta o conteúdo das linhas
# Utilização do comando For para leitura do IP    
    for ip in dump: 
     print('Verificando o ip: ', ip)
     print('-'*60)
     os.system('ping -n 2 {}'.format(ip))  #2 pacotes sendos enviados 
     print('-'*60)
     time.sleep(5) #para demorar 5 segundos a leitura entre um host e outro

